# Python Exercises

#### Written for the QuantEcon Africa Workshop (July 2023)
#### Author: [John Stachurski](http://johnstachurski.net/)

Before you attempt these exercises, we recommend that you read

1. the [lecture on NumPy](https://python-programming.quantecon.org/numpy.html),
2. the [lecture on MatPlotLib](https://python-programming.quantecon.org/matplotlib.html) and
3. the [lecture on SciPy](https://python-programming.quantecon.org/scipy.html).


## Exercises

### Exercise 1

Simulate and plot the correlated time series

$$
    x_{t+1} = \alpha \, x_t + \epsilon_{t+1}
    \quad \text{where} \quad
    x_0 = 0 
    \quad \text{and} \quad t = 0,\ldots,T
$$

Here $\{\epsilon_t\}$ is iid and standard normal.

In your solution, restrict your import statements to

In [1]:
from random import normalvariate
import matplotlib.pyplot as plt

Set $T=200$ and $\alpha = 0.9$

### Exercise 2

Generate 10000 data points from the [exponential distribution](https://en.wikipedia.org/wiki/Exponential_distribution) with density

$$
f(x; \alpha) = \alpha \exp(-\alpha x)
\qquad
(x > 0, \alpha > 0)
$$

taking $\alpha = 0.5$. Then

1. Plot a histogram of your sample and compare it to the density of the exponential distribution.
2. After looking up the maximum likelihood estimator of $\alpha$, compute the estimate given your data and check that it is in fact close to $\alpha$.

### Exercise 3

Using the same data set, implement maximum likelihood again, but this time pretending that you don't know the analytical expression for the maximum likelihood estimator.  Instead, set up the log likelihood function and maximize it numerically using a routine from `scipy.optimize`. (Have a look at the optimization examples from the scientific Python quickstart notebook.)

### Exercise 4

Recall that a discrete Lyapunov equation is a matrix equation of the form


\begin{equation}
    X = A X A' + M
\end{equation}


Here all matrices are $n \times n$ and $X$ is the unknown.  $A'$ is the transpose of $A$.  The equation has a unique solution if the spectral radius of $A$ is less than 1.

There is a solver for Lyapunov equations in SciPy.  Let's try it out with these matrices:

In [2]:
import numpy as np
A = np.array([[0, 1],[-1/2, -1]])
M = np.array([[0, 0], [0, 9]])

In [3]:
A

array([[ 0. ,  1. ],
       [-0.5, -1. ]])

In [4]:
M

array([[0, 0],
       [0, 9]])

Here's the solver and the solution.

In [5]:
from scipy.linalg import solve_discrete_lyapunov
solve_discrete_lyapunov(A, M)

array([[ 21.6, -14.4],
       [-14.4,  21.6]])

In fact it's possible to obtain this solution by iteration, starting with a guess $X_0$, such as $X_0 = M$, and then iterating on

$$
    X_{n+1} = A X_n A' + M
$$

Try to obtain the same solution using an iterative scheme.  (That is, start with $X_0$, then compute $X_1$, then $X_2$, etc.  You can stop when $X_{n+1}$ and $X_n$ are close, or by using some other simpler method.  But check that you get a result close to the solution above.)