# Scientific Libraries, Monte Carlo, and More Linear Algebra Exercises

<div align="right"><button><a href="https://colab.research.google.com/github/QuantEcon/workshop.africa-july2023/blob/main/day-04/exercise_set_4.ipynb"><img src="" heght="10px"/><img
    src="https://colab.research.google.com/assets/colab-badge.svg"
    alt="open with Colab" width="100px"/></a></button></div>

#### Written for the QuantEcon Africa Workshop (July 2023)
#### Author: [Smit Lunagariya](https://github.com/Smit-create), [Humphrey Yang](https://github.com/HumphreyYang) and [Shu Hu](https://shu-hu.com/)

This notebook contains the exercises on scientific libraries, Monte Carlo simulation, eigenvalues and eigenvectors.

In [19]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eig
from numpy.random import randn

## Exercises

Before you attempt these exercises, we recommend that you read

1. the [lecture on NumPy](https://python-programming.quantecon.org/numpy.html),
2. the [lecture on Matplotlib](https://python-programming.quantecon.org/matplotlib.html) and
3. the [lecture on SciPy](https://python-programming.quantecon.org/scipy.html).
4. the [lecture on Eigenvalues and Eigenvectrors](https://intro.quantecon.org/eigen_I.html).
5. the [An introduction to Monte Carlo](https://intro.quantecon.org/monte_carlo.html#an-introduction-to-monte-carlo)

### Exercise 1

Given a matrix $A$, compute the eigenvalues and eigenvectors and plot them.

In [20]:
A = np.array([[1, 4], [5, 7]])
A

array([[1, 4],
       [5, 7]])

In [21]:
# TODO: Write your code here

### Exercise 2

In this exercise, 

1. Draw 1000 independent draws from the standard normal distribution using [`scipy.stats`](https://docs.scipy.org/doc/scipy/reference/stats.html).

2. Calculate the sample mean and variance of the draws and compare them to the theoretical values.

3. Visualize the empirical distribution of the draws using a histogram. Mark the sample mean and $\pm$ one standard deviation using vertical lines.

4. Calculate the probability that a draw from the distribution is less than 0 and compare it to the proportion of the sample that is less than 0.

5. How do the results in question 3 change with different sample sizes? Try to draw 10, 100, 500, 1000, and 10000 samples, each with 100 times and plot the results.

Use the following imports to get started.

In [22]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

In [23]:
# TODO: Put your solution here

### Exercise 3

Consider a random variable $S$ in the following form

$$
S = \left ( \sum^M_{i=1} X_i \right )^p
$$

where $X_i \sim LN (\mu_i, \sigma_i)$, $M\in \mathbb N$ and $p$ is a positive number known to us.

#### Exercise 3.1

First let $M=1$ and $p=1$. Now we have

$$
    S = X_1
$$
where $X_1 \sim LN (\mu_1, \sigma_1)$.

Answer the following questions:

**Exercise 3.1.1**

Write down the analytical solutions to $\mathbb E S$ and $\mathop{\mathrm{Var}} S$.

In [24]:
# TODO: Write your answers in the markdown cell above

**Exercise 3.1.2**

Define two Python functions `mean_analytical` and `var_analytical` to compute the $\mathbb E S$ and $\mathop{\mathrm{Var}} S$ directly according to their analytical solutions.

In [25]:
def mean_analytical(μ_1, σ_1):
    # TODO: Write your code here
    pass

In [26]:
def var_analytical(μ_1, σ_1):
    # TODO: Write your code here
    pass

**Exercise 3.1.3**

Given 

In [27]:
n = 1_000_000
p = 1
μ_1 = 0.2
σ_1 = 0.1

Approximate $\mathbb E S$ by Monte Carlo simulation using loop. 

Compare the result with the analytical solution.

Hint. 
$$
\mathbb E S \approx  
\frac{1}{n} \sum_{i=1}^n S_i    
$$

In [28]:
# TODO: Write your code here

**Exercise 3.1.4**

With the same setup

In [29]:
n = 1_000_000
p = 1
μ_1 = 0.2
σ_1 = 0.1

and given $\mathbb ES$, approximate $\mathop{\mathrm{Var}} S$ by Monte Carlo simulation.

Compare it with the analytical solution.

Hint. Note that $\mathop{\mathrm{Var}} S = \mathbb E \left [S - \mathbb E S \right ]^2$.

In [30]:
# TODO: Write your code here

**Exercise 3.1.5**

With the same setup

In [31]:
n = 1_000_000
p = 1
μ_1 = 0.2
σ_1 = 0.1

Rewrite the loops in Exercises 1.1.3 and 1.1.4 with vectorization.

In [32]:
# TODO: Write your code here

#### Exercise 3.2

Let $M=3$. Then we have

$$
    S = (X_1 + X_2 + X_3)^p
$$
which is the same form as our lecture [here](https://intro.quantecon.org/monte_carlo.html#share-price-with-unknown-distribution).

Now we don't have analytical solutions for $\mathbb E S$ and $\mathop{\mathrm{Var}} S$.

We use the following values for $ p $ and each $ \mu_i $ and $ \sigma_i $.

In [33]:
n = 1_000_000
p = 0.5
μ_1, μ_2, μ_3 = 0.2, 0.8, 0.4
σ_1, σ_2, σ_3 = 0.1, 0.05, 0.2

In [34]:
def compute_mean_vectorized(n=1_000_000):
    X_1 = np.exp(μ_1 + σ_1 * randn(n))
    X_2 = np.exp(μ_2 + σ_2 * randn(n))
    X_3 = np.exp(μ_3 + σ_3 * randn(n))
    S = (X_1 + X_2 + X_3)**p
    return S.mean()

In [35]:
S_mean_mc_new = compute_mean_vectorized(n)
print("Monte Carlo simulation of ES in vectorization is ", S_mean_mc_new)  

Monte Carlo simulation of ES in vectorization is  2.2297060186121893


**Exercise 3.2.1** 

Given the monte carlo simulation of $\mathbb ES$, approximate $\mathop{\mathrm{Var}} S$ by Monte Carlo simulation using loop.

In [36]:
# TODO: Write your code here

**Exercise 3.2.2**

Rewrite the loop in Exercise 3.2.1 with vectorization.

In [37]:
# TODO: Write your code here

### Exercise 4

Simulate and plot the correlated time series

$$
    x_{t+1} = \alpha \, x_t + \epsilon_{t+1}
    \quad \text{where} \quad
    x_0 = 0 
    \quad \text{and} \quad t = 0,\ldots,T
$$

Here $\{\epsilon_t\}$ is iid and standard normal.

In your solution, restrict your import statements to

In [38]:
from random import normalvariate
import matplotlib.pyplot as plt

Set $T=200$ and $\alpha = 0.9$

In [39]:
# TODO: Put your solution here

### Exercise 5

On day 2, we generated 100000 data points from the [exponential distribution](https://en.wikipedia.org/wiki/Exponential_distribution) with density

$$
f(x; \alpha) = \alpha \exp(-\alpha x)
\qquad
(x > 0, \alpha > 0)
$$

taking $\alpha = 0.5$. Then

Using the same data set, implement maximum likelihood again, but this time pretending that you don't know the analytical expression for the maximum likelihood estimator.  Instead, set up the log likelihood function and maximize it numerically using a routine from `scipy.optimize`. 

(Hint: Have a look at the optimization examples from the scientific Python quickstart notebook.)

In [40]:
# TODO: Put your solution here

### Exercise 6

Recall that a discrete Lyapunov equation is a matrix equation of the form


\begin{equation}
    X = A X A^\top + M
\end{equation}


Here all matrices are $n \times n$ and $X$ is the unknown.  $A^\top$ is the transpose of $A$.  The equation has a unique solution if the spectral radius of $A$ is less than 1.

There is a solver for Lyapunov equations in SciPy.  Let's try it out with these matrices:

In [41]:
import numpy as np
A = np.array([[0, 1],[-1/2, -1]])
M = np.array([[0, 0], [0, 9]])

In [42]:
A

array([[ 0. ,  1. ],
       [-0.5, -1. ]])

In [43]:
M

array([[0, 0],
       [0, 9]])

Here's the solver and the solution.

In [44]:
from scipy.linalg import solve_discrete_lyapunov
solve_discrete_lyapunov(A, M)

array([[ 21.6, -14.4],
       [-14.4,  21.6]])

In fact it's possible to obtain this solution by iteration, starting with a guess $X_0$, such as $X_0 = M$, and then iterating on

$$
    X_{n+1} = A X_n A^\top + M
$$

Try to obtain the same solution using an iterative scheme.  (That is, start with $X_0$, then compute $X_1$, then $X_2$, etc.  You can stop when $X_{n+1}$ and $X_n$ are close, or by using some other simpler method.  But check that you get a result close to the solution above.)

In [45]:
# TODO: Put your solution here

### Exercise 7

The task is to compute an approximation to $\pi$ using Monte Carlo

Your hints are as follows:

* If $U$ is a bivariate uniform random variable on the unit square $(0, 1)^2$, then the probability that $U$ lies in a subset $B$ of $(0,1)^2$ is equal to the area of $B$.
* If $U_1,\ldots,U_n$ are IID copies of $U$, then, as $n$ gets large, the fraction that falls in $B$, converges to the probability of landing in $B$.
* For a circle, $area = \pi * radius^2$.

In [46]:
# TODO: Write your code here

### Exercise 8

Rewrite the Monte Carlo approximation of $\pi$ in Exercise 8 using vectorization.


In [ ]:
# TODO: Write your code here